/*
 * generated by Xtext
 */
package org.xtext.example.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GreetDSLUiModule extends org.xtext.example.dsl.ui.AbstractGreetDSLUiModule {
	public GreetDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	// contributed by org.eclipse.xtext.ui.generator.refactoring.RefactorElementNameFragment
	public Class<? extends org.eclipse.xtext.ui.refactoring.IRenameStrategy> bindIRenameStrategy() {
		return org.xtext.example.dsl.ui.refactoring.impl.GreetDSLRenameStrategy.class;
	}

}
