/*
 * generated by Xtext
 */
package org.xtext.example.dsl.ui.contentassist

import org.xtext.example.dsl.ui.contentassist.AbstractGreetDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class GreetDSLProposalProvider extends AbstractGreetDSLProposalProvider {
}
