/*
* generated by Xtext
*/
package org.xtext.example.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GreetDSLStandaloneSetup extends GreetDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new GreetDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

