/*
 * generated by Xtext
 */
package org.xtext.example.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GreetDSLRuntimeModule extends org.xtext.example.dsl.AbstractGreetDSLRuntimeModule {

}
